services:
  backend-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-server
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: faruk123
      DATABASE_NAME: summarizer
      DATABASE_HOST: database
      DATABASE_PORT: "5432"
      PYTHONUNBUFFERED: "1"
    ports:
      - "80:80"
    volumes:
      - ./backend/logs:/code/logs
    depends_on:
      - database
    restart: unless-stopped
  
  database:
    image: postgres:15-alpine
    container_name: database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=faruk123
      - POSTGRES_DB=summarizer

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - backend-server
    restart: unless-stopped
  

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: -config.file=/mnt/config/promtail-config.yaml
    volumes:
      - ./monitoring/promtail/config.yml:/mnt/config/promtail-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail_positions:/positions
    depends_on:
      - loki
    restart: unless-stopped
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/mnt/config/loki-config.yaml
    ports:
      - 3100:3100
    volumes:
      - ./monitoring/loki/config.yml:/mnt/config/loki-config.yaml
      - loki_data:/loki
    restart: unless-stopped


volumes:
  postgres_data:
    driver: local
  prometheus_data:
    driver: local
  grafana-data:
    driver: local
  loki_data:
    driver: local
  promtail_positions:
    driver: local